# Generated by Django 4.1.7 on 2023-03-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="podcast/images")),
                ("description", models.TextField()),
                ("time", models.DateTimeField()),
                ("youtube_link", models.CharField(max_length=255)),
                ("spotify_link", models.CharField(max_length=255)),
                ("guest", models.CharField(max_length=255)),
            ],
        ),
    ]
