# Generated by Django 4.1.7 on 2023-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_alter_podcast_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="podcast",
            old_name="guest",
            new_name="guests",
        ),
        migrations.RemoveField(
            model_name="podcast",
            name="image",
        ),
        migrations.AddField(
            model_name="podcast",
            name="image_link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
