# Generated by Django 4.1.7 on 2023-03-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0004_guest_remove_podcast_guests_podcast_guests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="socials",
            new_name="linkedin",
        ),
        migrations.AddField(
            model_name="guest",
            name="photo_link",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="podcast",
            name="guests",
            field=models.ManyToManyField(related_name="podcasts", to="podcast.guest"),
        ),
    ]
